### PR TITLE
fix of https://github.com/mattjgalloway/MJGFoundation/issues/6 for suppo...

### PR DESCRIPTION
**Pull request by Speakus**
...rting iOS SDK 7 - 8 and OSX 10.9

### CODE REVIEW

**Comment by kenji21** [comment]
Just tested this in an iOS project : it works
EDIT : on xcode5 created project, it doesn't works.

**Comment by mattjgalloway** [comment]
Thanks @kenji21!

**Comment by kenji21** [comment]
Just created a new Xcode project, setted deployment target to 6.0, and use setMinimumBackgroundFetchInterval which is iOS7+ in appDelegate :

```
- (BOOL)application:(UIApplication *)application
 didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
     [application setMinimumBackgroundFetchInterval:12];
```

It doesn't show the warning (I continue research of what has changed because Xcode4 created project is OK, deployment target also setted to 6.0)

**Comment by mattjgalloway** [comment]
Thanks @kenji21. Let me know if you find anything. Ideally it would be better to hook into the new clang built-in way of defining deprecation (which is why this broke in the first place). But I had a look last year when Xcode 5 came out and couldn't find a way to do it.

**Comment by kenji21** [comment]
Here is the compile command that show a warning :

```
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wstrict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCONFIGURATION_Debug -DOKLOG_ENABLED=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk -fstrict-aliasing -fprofile-arcs -ftest-coverage -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote $(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/AppName-generated-files.hmap -I$(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/AppName-own-target-headers.hmap -I$(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/AppName-all-target-headers.hmap -iquote $(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/AppName-project-headers.hmap -I$(DERIVED_DATA)/Build/Products/Debug-iphoneos/include  -I$(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/DerivedSources/armv7 -I$(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/DerivedSources -F$(DERIVED_DATA)/Build/Products/Debug-iphoneos -F/Applications/Xcode.app/Contents/Developer/Library/Frameworks -DDEBUG=1 -include $(DERIVED_DATA)/Build/Intermediates/PrecompiledHeaders/AppName_Prefix-gjrptocmrskfrseqqaeqzgizwfmy/AppName_Prefix.pch -MMD -MT dependencies -MF $(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/Objects-normal/armv7/CustomMoviePlayerViewController.d --serialize-diagnostics $(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/Objects-normal/armv7/CustomMoviePlayerViewController.dia -c /Users/kenji/openium/iphone/clients/AppName-trunk/src/iphone/Classes/CustomMoviePlayerViewController.m -o $(DERIVED_DATA)/Build/Intermediates/AppName.build/Debug-iphoneos/AppName.build/Objects-normal/armv7/CustomMoviePlayerViewController.o
```

and here the one that must show a warning but doesn't :

```
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/kenji/Library/Developer/Xcode/DerivedData/ModuleCache -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote $(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/test-generated-files.hmap -I$(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/test-own-target-headers.hmap -I$(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/test-all-target-headers.hmap -iquote $(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/test-project-headers.hmap -I$(DERIVED_DATA)/Build/Products/Debug-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I$(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/DerivedSources/arm64 -I$(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/DerivedSources -F$(DERIVED_DATA)/Build/Products/Debug-iphoneos -include $(DERIVED_DATA)/Build/Intermediates/PrecompiledHeaders/test-Prefix-gbnxrrlfnhmqbsfezaytdcqvvkie/test-Prefix.pch -MMD -MT dependencies -MF $(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/Objects-normal/arm64/CFKAppDelegate.d --serialize-diagnostics $(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/Objects-normal/arm64/CFKAppDelegate.dia -c /Users/kenji/Desktop/test/test/CFKAppDelegate.m -o $(DERIVED_DATA)/Build/Intermediates/test.build/Debug-iphoneos/test.build/Objects-normal/arm64/CFKAppDelegate.o
```

**Comment by kenji21** [comment]
Found it : you should set "Enable Modules (C and Objective-C)" to No
Just discover this by using "working" command parameters in the the second command :

```
error: modules extension to C was enabled in PCH file but is currently disabled
```

**Comment by mattjgalloway** [comment]
Oh, yes, of course. Modules is going to totally screw with this. I think maybe the right solution is to actually deprecate MJGAvailability unfortunately. It's not the future. Apple should provide a way to do this, and we should file radars.

**Comment by kenji21** [comment]
As of Xcode help description, we will disable this and continue using MJGAvailability in order to not lose time by not seeing a "Too new API usage". Slower build... just bought a SSD :-).

Enables the use of modules for system APIs.  System headers are imported as semantic modules instead of raw headers.  This can result in faster builds and project indexing.  [CLANG_ENABLE_MODULES, -fmodules]

Maybe adding a word on top of header would help.

**Comment by kenji21** [comment]
Just submitted an bugreport to Apple.

**Pull request merged**
