### PR TITLE
Add newer iOS versions to MJGAvailability.h

### PR DESCRIPTION
**Pull request by gabrielmaldi**
Hey, thanks for creating `MJGAvailability.h`! I've been using it for a while now.

I added `iOS 8` and `iOS 9` (and minor versions too) so that newer APIs also get detected.

### CODE REVIEW

**Comment by warpling** [comment]
++

**Comment by kenji21** [comment]
Xcode 7.3 make this prefixed header changes obsolete by adding -Wpartial-availability flags.

**Comment by gabrielmaldi** [comment]
@kenji21 you're right. Xcode 7.3 now supports adding

```
WARNING_CFLAGS = (
  "-Wpartial-availability"
);
```

to `buildSettings` in `project.pbxproj`, which generates this kind of warnings:

`'UIActivityTypeAirDrop' is partial: introduced in iOS 7.0`

**Comment by warpling** [comment]
Oh beautiful! This should be posted everywhere!

**Comment by mattjgalloway** [comment]
Also, see Infer's new check:
http://fbinfer.com/docs/linters-bug-types.html#UNAVAILABLE_API_IN_SUPPORTED_IOS_SDK

Closing this out as there's multiple options for this now, and MJGAvailability is not the right solution any more.

**Pull request closed without merging**
